server:
  port: 8011

spring:
  redis:
    database: 0
    timeout: 3000
    password: xuzzb
    #    sentinel:    #哨兵模式
    #      master: mymaster #主服务器所在集群名称
    #      nodes: 192.168.65.60:26379,192.168.65.60:26380,192.168.65.60:26381
    cluster:
      nodes: 172.17.0.2:8001,172.17.0.3:8002,172.17.0.4:8003,172.17.0.2:8004,172.17.0.3:8005,172.17.0.4:8006
    lettuce:
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 100
        max-wait: 1000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web?serverTimezone=GMT%2B8
    username: root
    password: 123456


