spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/world?serverTimezone=GMT%2B8
server:
  port: 9933

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false